# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Tela_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(347, 383)
        Menu.setStyleSheet("background-color: rgb(0, 70, 112);")
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(-10, 50, 531, 281))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.saldo_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.saldo_lineEdit.setEnabled(False)
        self.saldo_lineEdit.setGeometry(QtCore.QRect(20, 40, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.saldo_lineEdit.setFont(font)
        self.saldo_lineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.saldo_lineEdit.setText("")
        self.saldo_lineEdit.setFrame(False)
        self.saldo_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.saldo_lineEdit.setObjectName("saldo_lineEdit")
        self.deposito_Button = QtWidgets.QPushButton(self.frame)
        self.deposito_Button.setGeometry(QtCore.QRect(20, 90, 71, 41))
        self.deposito_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deposito_Button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.deposito_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("deposito.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deposito_Button.setIcon(icon)
        self.deposito_Button.setIconSize(QtCore.QSize(64, 64))
        self.deposito_Button.setCheckable(False)
        self.deposito_Button.setChecked(False)
        self.deposito_Button.setAutoRepeat(False)
        self.deposito_Button.setAutoExclusive(False)
        self.deposito_Button.setAutoDefault(False)
        self.deposito_Button.setDefault(False)
        self.deposito_Button.setFlat(True)
        self.deposito_Button.setObjectName("deposito_Button")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.saque_Button = QtWidgets.QPushButton(self.frame)
        self.saque_Button.setGeometry(QtCore.QRect(10, 160, 91, 61))
        self.saque_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saque_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("saque.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saque_Button.setIcon(icon1)
        self.saque_Button.setIconSize(QtCore.QSize(64, 64))
        self.saque_Button.setFlat(True)
        self.saque_Button.setObjectName("saque_Button")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.transferencia_Button = QtWidgets.QPushButton(self.frame)
        self.transferencia_Button.setGeometry(QtCore.QRect(120, 80, 61, 51))
        self.transferencia_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transferencia_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("transferencia.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transferencia_Button.setIcon(icon2)
        self.transferencia_Button.setIconSize(QtCore.QSize(52, 52))
        self.transferencia_Button.setFlat(True)
        self.transferencia_Button.setObjectName("transferencia_Button")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(110, 130, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.extrato_Button = QtWidgets.QPushButton(self.frame)
        self.extrato_Button.setGeometry(QtCore.QRect(120, 160, 61, 61))
        self.extrato_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.extrato_Button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("extrato.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extrato_Button.setIcon(icon3)
        self.extrato_Button.setIconSize(QtCore.QSize(120, 120))
        self.extrato_Button.setFlat(True)
        self.extrato_Button.setObjectName("extrato_Button")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(130, 220, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.cliente_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cliente_lineEdit.setEnabled(False)
        self.cliente_lineEdit.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cliente_lineEdit.setFont(font)
        self.cliente_lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.cliente_lineEdit.setText("")
        self.cliente_lineEdit.setFrame(False)
        self.cliente_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.cliente_lineEdit.setObjectName("cliente_lineEdit")
        self.sair_Button = QtWidgets.QPushButton(self.centralwidget)
        self.sair_Button.setGeometry(QtCore.QRect(260, 340, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.sair_Button.setFont(font)
        self.sair_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sair_Button.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0)\n"
"}\n"
"")
        self.sair_Button.setCheckable(False)
        self.sair_Button.setChecked(False)
        self.sair_Button.setObjectName("sair_Button")
        Menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 347, 21))
        self.menubar.setObjectName("menubar")
        Menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Menu)
        self.statusbar.setObjectName("statusbar")
        Menu.setStatusBar(self.statusbar)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)
        Menu.setTabOrder(self.cliente_lineEdit, self.saldo_lineEdit)
        Menu.setTabOrder(self.saldo_lineEdit, self.deposito_Button)
        Menu.setTabOrder(self.deposito_Button, self.transferencia_Button)
        Menu.setTabOrder(self.transferencia_Button, self.saque_Button)
        Menu.setTabOrder(self.saque_Button, self.extrato_Button)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "MainWindow"))
        self.label.setText(_translate("Menu", "Conta"))
        self.label_2.setText(_translate("Menu", "Depositar"))
        self.label_3.setText(_translate("Menu", "Saque"))
        self.label_4.setText(_translate("Menu", " Transferencia"))
        self.label_5.setText(_translate("Menu", "Extrato"))
        self.sair_Button.setText(_translate("Menu", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QMainWindow()
    ui = Ui_Tela_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())

